Update monitoring-test.yml

diff --git a/.github/workflows/monitoring-test.yml b/.github/workflows/monitoring-test.yml
--- a/.github/workflows/monitoring-test.yml
+++ b/.github/workflows/monitoring-test.yml
@@ -27,7 +27,7 @@ jobs:
       - name: Simulating a failure
         run: |
           echo "This job is supposed to fail"
-          exit 0  # Forces the job to fail
+          exit 1  # Forces the job to fail
           
   new_job:
      runs-on: ubuntu-latest
@@ -36,4 +36,13 @@ jobs:
       - name: Simulating a pass
         run: |
           echo "This job is supposed to pass"
-          exit 0  # Forces the job to fail
+          exit 0  # Forces the job to pass
+
+  test_job:
+     runs-on: ubuntu-latest
+     
+     steps:        
+      - name: Simulating a test
+        run: |
+          echo "This job is newly added and is supposed to pass"
+          exit 0  # Forces the job to pass
