Update monitoring-test.yml

diff --git a/.github/workflows/monitoring-test.yml b/.github/workflows/monitoring-test.yml
--- a/.github/workflows/monitoring-test.yml
+++ b/.github/workflows/monitoring-test.yml
@@ -19,3 +19,8 @@ jobs:
         with:
           name: small-artifact
           path: artifact.txt
+          
+      - name: Simulating a failure
+        run: |
+          echo "This job is supposed to fail"
+          exit 1  # Forces the job to fail
